definitions:
  controlador.request:
    properties:
      activo:
        type: boolean
      altura:
        type: number
      apellido:
        type: string
      edad:
        type: integer
      email:
        type: string
      fechaCreacion:
        type: string
      nombre:
        type: string
    type: object
info:
  contact:
    email: support@nico.io
    name: API Nico
    url: http://www.nico.io/support
  description: This API Handle MeLi products.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://hola.quetal
  title: MeLi Bootcamp API
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: get users
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Lista de usuarios
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: store users
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: User to store
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controlador.request'
      produces:
      - application/json
      responses: {}
      summary: Store users
      tags:
      - Users
swagger: "2.0"
